name: LIKWID Build Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-accessdaemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make accessdaemon
      run: make ACCESSMODE=accessdaemon

  build-perfevent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make perf_event
      run: make ACCESSMODE=perf_event
